# MySQL 配置
[mysql]
host = 127.0.0.1
user = root
# 如果是本机mysql，则把端口号改为3306，这里使用docker容器的mysql
port = 3306
password = 123456
database = subjects_kg
# Redis 配置
[redis]
host = 127.0.0.1
port = 6379
password = 1234
db = 0
# Milvus 配置
[milvus]
# 如果使用云五服务器，这里应该改为云服务器的IP
host = 127.0.0.1
port = 19530
database_name = itcast
collection_name = edurag_gz7
# LLM 配置
[llm]
model = qwen-plus
dashscope_api_key = sk-ws-H.RXHIYHD.FBhP.MEYCIQDIRYYU5sZj0RN9X_xgIlF7R4GjVlFalfIw-Z2Br1xCqgIhAMnfUtngxmI7EsfoH7ML7pPQ82mbNd-4bbFrJDMRAesi
dashscope_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1

# 检索参数配置
[retrieval]
parent_chunk_size = 1200
child_chunk_size = 300
chunk_overlap = 50
retrieval_k = 10
candidate_m = 3

# 应用配置
[app]
valid_sources = ["ai", "java", "test", "ops", "bigdata"]
customer_service_phone = 10086

# 日志配置
[logger]
log_file = D:/EduRAG_V7.5_gz7/07-live_code/01.project_code_gz7/integrated_qa_system/logs/app.log